# Generated by Django 4.1 on 2022-08-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(default='', max_length=10)),
                ('rubro', models.CharField(choices=[('NO APLICA', 'NO APLICA'), ('AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA', 'AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA'), ('EXPLOTACIÓN DE MINAS Y CANTERAS', 'EXPLOTACIÓN DE MINAS Y CANTERAS'), ('INDUSTRIA MANUFACTURERA', 'INDUSTRIA MANUFACTURERA'), ('SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO'), ('SUMINISTRO DE AGUA; EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN', 'SUMINISTRO DE AGUA; EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN'), ('CONSTRUCCIÓN', 'CONSTRUCCIÓN'), ('COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHICULOS AUTOMOTORES Y MOTOCICLETAS', 'COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHICULOS AUTOMOTORES Y MOTOCICLETAS'), ('TRANSPORTE Y ALMACENAMIENTO', 'TRANSPORTE Y ALMACENAMIENTO'), ('ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS', 'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS'), ('INFORMACIÓN Y COMUNICACIONES', 'INFORMACIÓN Y COMUNICACIONES'), ('ACTIVIDADES FINANCIERAS Y DE SEGUROS', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS'), ('ACTIVIDADES INMOBILIARIAS', 'ACTIVIDADES INMOBILIARIAS'), ('ACTIVIDADES PROFESIONALES, CIENTIFICAS Y TÉCNICAS', 'ACTIVIDADES PROFESIONALES, CIENTIFICAS Y TÉCNICAS'), ('ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO', 'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO'), ('ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA'), ('ENSEÑANZA', 'ENSEÑANZA'), ('ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL'), ('ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREATIVAS'), ('OTRAS ACTIVIDADES DE SERVICIOS', 'OTRAS ACTIVIDADES DE SERVICIOS'), ('ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES; ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES', 'ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES; ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES'), ('ACTIVIDADES DE ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES', 'ACTIVIDADES DE ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES')], default='', max_length=90)),
                ('razon_socila', models.CharField(default='', max_length=80)),
                ('telefono_cliente', models.IntegerField()),
                ('email_cliente', models.CharField(default='', max_length=200)),
                ('direccion_cliente', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(default='', max_length=10)),
                ('telefono_profesional', models.IntegerField()),
                ('nombre_profesional', models.CharField(default='', max_length=80)),
                ('apellidos_profesional', models.CharField(default='', max_length=80)),
                ('email_profesional', models.CharField(default='', max_length=100)),
                ('direccion_profesional', models.CharField(default='', max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], default='', max_length=200)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Binario', 'No Binario')], default='', max_length=10)),
            ],
        ),
    ]
